<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\chords-db-guitar.json" LogicalName="ChordVisualizer.Core.Data.chords-db-guitar.json" />
  </ItemGroup>

</Project>
